# Generated by Django 4.2 on 2023-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
